### PR TITLE
(fix): broken ref to submodule 'BiglyBT-plugin-mlDHT'

### PR DESCRIPTION
**Pull request by javulticat**
## Problem

Hi!  I noticed that the pipeline for your Github Action [`pages-build-deployment`](https://github.com/BiglySoftware/BiglyBT-Android/actions/workflows/pages/pages-build-deployment) has been consistently failing for nearly a month, with 8 consecutive failed runs since Nov 25th.  Upon investigation, it appears the failures are all related to a change made in https://github.com/BiglySoftware/BiglyBT-Android/commit/9ffaab710b72d5943600cceb448d1d08fefaebff.  Specifically, the problem appears to be caused by [the change made to the commit that the `BiglyBT-plugin-mlDHT` submodule references](https://github.com/BiglySoftware/BiglyBT-Android/commit/9ffaab710b72d5943600cceb448d1d08fefaebff#diff-f339ec6de79be521b165ec6d3cbdd9b1d01c65da3c50ec2e24fba05d4976a6e5): the submodule's commit ref was changed from https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/1bf24e39aab16a9a4ffe9a8246c5d174b416ec37 to https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/77ffcf1ac56d62c700e3d4000e50c495587a5f0d.

### Reproduction

The reason that change is causing problems is that the new commit the `BiglyBT-plugin-mlDHT` submodule is now supposed to reference does not currently appear to exist in the [`BiglyBT-plugin-mlDHT` repository](https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT).  For example, if you click the link to that commit (https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/77ffcf1ac56d62c700e3d4000e50c495587a5f0d), you'll get a 404.  You'll also get a 404 by clicking the [current link to the `BiglyBT-plugin-mlDHT` submodule](https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/tree/77ffcf1ac56d62c700e3d4000e50c495587a5f0d) from this repo:

image

## Solution

Looking at the current [commit history on the `android` branch of `BiglyBT-plugin-mlDHT`](https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commits/android/), the only commit more recent than https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/1bf24e39aab16a9a4ffe9a8246c5d174b416ec37 that currently exists is https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/7df646696050c490ec1e37c8ce69340b60a8ec74.  Therefore, it can be deduced that if https://github.com/BiglySoftware/BiglyBT-Android/commit/9ffaab710b72d5943600cceb448d1d08fefaebff intended to update the commit referenced by the `BiglyBT-plugin-mlDHT` submodule to a more recent commit than https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/1bf24e39aab16a9a4ffe9a8246c5d174b416ec37, then https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/7df646696050c490ec1e37c8ce69340b60a8ec74 is the only commit that would qualify.

Thus, the only change this PR makes is causing https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/7df646696050c490ec1e37c8ce69340b60a8ec74 (as identified above) to be the commit that will now be referenced by the `BiglyBT-plugin-mlDHT` submodule (replacing its current problematic reference to the non-extant https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/commit/77ffcf1ac56d62c700e3d4000e50c495587a5f0d).

### Verification

It's expected that the intended effect of merging this PR will automatically become fully verifiable within minutes after its merge, as the [`pages-build-deployment`](https://github.com/BiglySoftware/BiglyBT-Android/actions/workflows/pages/pages-build-deployment) pipeline should get triggered by the merge commit created by merging this PR.

#### Verification criteria:

_Ordered chronologically_

- [ ] After merge, it is confirmed that the link to the `BiglyBT-plugin-mlDHT` submodule on Github no longer leads to a 404 page, but instead leads successfully to this page: https://github.com/BiglySoftware/BiglyBT-plugin-mlDHT/tree/7df646696050c490ec1e37c8ce69340b60a8ec74  _[Immediately]_
- [ ] After merge, it is confirmed that the [`pages-build-deployment`](https://github.com/BiglySoftware/BiglyBT-Android/actions/workflows/pages/pages-build-deployment) pipeline associated with this PR's merge commit ran successfully  _[Within minutes]_
- [ ] After merge, it is confirmed that the latest deployment of [`github-pages`](https://github.com/BiglySoftware/BiglyBT-Android/deployments/github-pages) changed from having been deployed a month ago by pipeline `#148` to having been deployed recently by the pipeline associated with this PR's merge commit (the same pipeline the above criterion refers to)  _[Within minutes]_

#### _fin_

Hope this helps!

### CODE REVIEW

**Comment by Dimezis** [comment]
Thank you for this, it really helped me with my fork

**Comment by javulticat** [comment]
@Dimezis, glad to hear it!  Did it resolve the submodule-related Issue you were having (#242)?

Gentle ping for @TuxPaper - not sure if this PR is on your radar.  Looks like you're maintaining this repo on your own, so that'd be completely understandable 🙃.  As a fellow FLOSS maintainer/developer who has been there - and a long-time user of (and major evangelist for 🗣️) `BiglyBT` on Android - let me know if there's anything I can do to help!

**Comment by Dimezis** [comment]
> Did it resolve the submodule-related Issue you were having (https://github.com/BiglySoftware/BiglyBT-Android/issues/242)?

Unfortunately no. It works fine on your branch, and on the latest master with changes from your branch.
But if you sync submodules on top of that, the server no longer starts.

**Comment by TuxPaper** [comment]
Thanks, I've pushed the android BiglyBT-plugin-mlDHT branch to be up-to-date with the master branch and synced BiglyBT-Android to point to the new reference

**Pull request closed without merging**
