### PR TITLE
Cleanup gitignore

### PR DESCRIPTION
**Pull request by Shusshu**
Remove .idea folder to avoid clashes between different computers

### CODE REVIEW

**Comment by TuxPaper** [comment]
hmm, I'm not sure about this one.  The idea files kept are based on https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore which is based on 
 https://intellij-support.jetbrains.com/hc/en-us/articles/206544839 

Wouldn't the lack of these files make it harder for someone who want to easily get started on the project?

**Comment by Shusshu** [comment]
Well using maven nobody needs IDE specific files, plus on my setup these files where automatically changed by IntelliJ which in turns would end up in a commit and disturb your setup ;)

**Comment by TuxPaper** [comment]
I've removed misc.xml and *.iml (iml was already in the gitignore, but the files were in git), hopefully that makes things a little bit better for you.

I like keeping the other IntelliJ settings, like copyright and eclipse formatter and others, so that anyone new to the project has a good starting point (and doesn't send pull requests with unformatted code)

I believe you can do something like `git update-index --assume-unchanged <file>` locally, but I'm not sure of all the side affects of that.

**Comment by Shusshu** [comment]
Great that's much better

**Pull request closed without merging**
